apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 5000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP